import argparse
import json
import logging
from pathlib import Path
import pandas as pd
import numpy as np

# Configure Logging
logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger(__name__)

def evaluate_daily_alpha(input_path: str):
    input_file = Path(input_path)
    if not input_file.exists():
        logger.error(f"Error: Input file '{input_file}' not found.")
        return

    logger.info(f"Loading data from: {input_file}")
    
    # 1. Parse JSONL Data
    data = []
    with open(input_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
                # Ensure the row has the required keys
                if "date" in row and "portfolio_value" in row:
                    data.append({
                        "date": row["date"],
                        "portfolio_value": float(row["portfolio_value"])
                    })
            except json.JSONDecodeError:
                logger.warning("Skipping invalid JSON line.")

    if not data:
        logger.error("No valid data found in the input file.")
        return

    # 2. Convert to DataFrame and Calculate Metrics
    df = pd.DataFrame(data)
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values('date').reset_index(drop=True)
    
    # Calculate Daily Returns
    df['daily_return'] = df['portfolio_value'].pct_change()
    
    # Drop the first NaN value
    df = df.dropna(subset=['daily_return']).copy()
    
    # Metric Calculations
    returns = df['daily_return']
    
    total_days = len(returns)
    if total_days == 0:
        logger.warning("Not enough data to calculate returns.")
        return
        
    winning_days = returns[returns > 0]
    losing_days = returns[returns < 0]
    flat_days = returns[returns == 0]
    
    num_wins = len(winning_days)
    num_losses = len(losing_days)
    num_flat = len(flat_days)
    
    hit_rate = num_wins / total_days if total_days > 0 else 0.0
    
    avg_daily_return = returns.mean()
    avg_win = winning_days.mean() if num_wins > 0 else 0.0
    avg_loss = losing_days.mean() if num_losses > 0 else 0.0
    
    payoff_ratio = abs(avg_win / avg_loss) if avg_loss != 0 else float('inf')
    
    # Annualized Sharpe Ratio (Assume Risk-Free Rate = 0)
    std_dev = returns.std()
    sharpe_ratio = (avg_daily_return / std_dev) * np.sqrt(252) if std_dev > 0 else 0.0

    # 3. Print Beautiful Report
    print("\n" + "="*50)
    print("🚀 PURE 1-DAY FORWARD ALPHA EVALUATION 🚀")
    print("="*50)
    print(f"Data Period:     {df['date'].min().strftime('%Y-%m-%d')} to {df['date'].max().strftime('%Y-%m-%d')}")
    print(f"Total Trading Days Evaluated: {total_days}")
    print("-" * 50)
    print(f"WIN / LOSS TALLY:")
    print(f"  Win Days:      {num_wins} ({num_wins/total_days*100:.1f}%)")
    print(f"  Loss Days:     {num_losses} ({num_losses/total_days*100:.1f}%)")
    print(f"  Flat Days:     {num_flat} ({num_flat/total_days*100:.1f}%)")
    print("-" * 50)
    print(f"KEY METRICS:")
    print(f"  Hit Rate (Win %):     {hit_rate*100:.2f}%")
    print(f"  Avg Daily Return:     {avg_daily_return*100:.4f}%")
    print(f"  Avg Win:              {avg_win*100:.2f}%")
    print(f"  Avg Loss:             {avg_loss*100:.2f}%")
    print(f"  Payoff Ratio:         {payoff_ratio:.2f}x")
    print(f"  Ann. Sharpe Ratio:    {sharpe_ratio:.2f}")
    print("="*50 + "\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate pure 1-day forward alpha from optimization JSONL output")
    parser.add_argument("--input-file", type=str, required=True, help="Path to the .jsonl file generated by the zero-friction backtest")
    
    args = parser.parse_args()
    evaluate_daily_alpha(args.input_file)
